all: printargs hello calcstat bitcount

printargs: printargs.c
	gcc -std=c99 -Wall -Wextra -pedantic printargs.c -o printargs

hello: hello.c
	gcc -std=c99 -Wall -Wextra -pedantic hello.c -o hello

calcstat: calcstat.c
	gcc -std=c99 -Wall -Wextra -pedantic calcstat.c -o calcstat

bitcount: bitcount.c
	gcc -std=c99 -Wall -Wextra -pedantic bitcount.c -o bitcount

clean:
	rm -f hello printargs calcstat bitcount a.out


